### ISSUE TITLE
Add wiki page about keys as arrays

### ISSUE THREAD

**Issue by tordans** [Locale/localeapp#119]
I was looking all over the internet for some explanation about how to do this … why is it not documented in your wiki? (https://github.com/Locale/localeapp/wiki)

_Suggested Content of the Wiki Page:_
Create a translation like this and localeapp will transform it in a list-translation, highlighting it by changing font and background-color.
your.translation.key:

``` yml

---
- lorem
- ipsum
- dolores
```

Translations like this will be available as an array ['lorem', 'ipsum', 'dolores'] right when called in your rails app t('your.translation.key').

Note that the corresponding yml-structure in you en.yml will look like this:

``` yml
you:
  translation:
    key:
    - lorem
    - ipsum
    - dolores
```

Example usages: Rails uses this for it's array of week days.

_Tips:_

It's recommended to add some savety features in your app. Otherwise a misstranslated/missformated translation could 500-break your app. You could, for example, always call the key with a default t('your.translation.key', default: []). In addition you could wrap it in a helper

``` ruby
def keywords
  keywords = I18n.t('my.seo.keywords', default: [])
  keywords.is_a?(Array) ? keywords : []
end
```

**Comment by tjouan** [comment]
@tordans thank you for the suggestion, and those examples.

In this same "missing" wiki page, we should also mention "boolean"
values, like for arrays Localeapp has special behavior to edit them.

**Comment by tjouan** [comment]
@tordans here is the new page:
https://github.com/Locale/localeapp/wiki/Special-values-(arrays,-boolean)-handled-by-Localeapp

I made some small edits: improved YAML example and changed some
formatting.

**Comment by sarojkh** [comment]
@tjouan The wiki page doesn't mention how to send 'array as translations' from within the command line (`localeapp add)`. I searched around and couldn't find a solution. Is that even possible?

**Comment by sarojkh** [comment]
> @tjouan The wiki page doesn't mention how to send 'array as translations' from within the command line (`localeapp add)`. I searched around and couldn't find a solution. Is that even possible?

cc @thibaultdalban

**Comment by thibaultdalban** [comment]
@sarojkh, unfortunately, it's not possible to do that. A workaround could be to create a little YAML file for your key and then push it.

**Comment by sarojkh** [comment]
@thibaultdalban Thanks for the quick reply. 

So, does a `localeapp push <file_with_translations>` upsert translations in the file to the server , or will it replace the overall translations in the server with the ones in the file?

**Comment by thibaultdalban** [comment]
@sarojkh, it will replace the overall translations in the server with the ones in the file.
