### ISSUE TITLE
Disable localeapp send_missing_translations for ActiveAdmin

### ISSUE THREAD

**Issue by RudthMael** [Locale/localeapp#124]
I'd like to disable it as there is no need for translations.

I added skip_before_filter :send_missing_translations and it still sends messages to the service.

Is there any way to disable localeapp for a given path or controller?

**Comment by michaelbaudino** [comment]
@RudthMael sorry for the very long delay but, as @timoschilling mentioned, activeadmin/activeadmin#3524 has now been merged so all ActiveAdmin keys are now namespaced.

Anyway, here are a few possible solutions (pick whichever fits best for you):
* to prevent a Rails controller from polling/sending translations, use:
    ```ruby
    class PostController < ApplicationController do
      skip_before_filter :handle_translation_updates
      skip_after_filter :send_missing_translations
    end
    ```

* to prevent an ActiveAdmin controller from polling/sending translations:
    ```ruby
    ActiveAdmin.register Post do
      controller do
        skip_before_filter :handle_translation_updates
        skip_after_filter :send_missing_translations
      end
    end
   ```

* to prevent all ActiveAdmin controllers from polling/sending translations:
    ```ruby
    # /config/initializers/active_admin.rb
    ActiveAdmin.setup do |config|
      config.skip_before_filter :handle_translation_updates
      config.skip_after_filter :send_missing_translations
    end
    ```

I hope one of those works for you.

**Comment by michaelbaudino** [comment]
Closing for now, feel free to reopen if none of those solutions work.
