### ISSUE TITLE
Rails: Missing translations not sent anymore

### ISSUE THREAD

**Issue by A5308H** [Locale/localeapp#157]
It seems like a similar problem like the one in https://github.com/Locale/localeapp/issues/126.
Using I18.t() instead of t() works. But with t() the log does not show the

    ** [Localeapp] translation missing: de-CH.dashboard

I would expect and nothing gets sent to locale.

I don't have a clear indication of when the change happened. (The translators didn't want to bother us programmers again, with the same thing.) But in https://github.com/Locale/localeapp/issues/126 @markedmondson wrote he saw the problem in RCs of Rails 4.1 which lead me here:

https://github.com/kassio/rails/commit/433628a45c2f5dd04b115af1b5579dac75255c67

which might mean something to you. This discussion: https://github.com/rails/rails/issues/13429 might also be helpful.

Thanks a lot in advance!
Andy

**Comment by michaelbaudino** [comment]
This should be fixed in gem version 0.9.1
