### ISSUE TITLE
Confusion over the documentation of two of the configs

### ISSUE THREAD

**Issue by redbar0n** [Locale/localeapp#165]
Confusion over the documentation of two of the configs (accessors)

In the documentation here:
`lib/localeapp/configuration.rb`

```
# The names of environments where notifications are sent
# (defaults to 'development')
attr_accessor :sending_environments
```

Does this mean the names of environments where notifications are sent _(to localeapp.com)_ **_from**_ ?

This clarification is necessary to eliminate the ambiguity. As it currently stands you could interpret it as the environments that are being sent _to_.

---

```
# The names of environments where updates aren't pulled
# (defaults to 'development')
attr_accessor :polling_environments
```

This description is confusing, and maybe wrong? Re: http://stackoverflow.com/questions/2761204/whats-the-difference-between-polling-and-pulling

I read in the [localeapp wiki](https://github.com/Locale/localeapp/wiki/Deploy-a-Locale-Backed-Application-to-Heroku) that :polling_environments means _allow localeapp to check for new translations in these environments_.

And [on this other localeapp wiki page](https://github.com/Locale/localeapp/wiki/Configure-the-Locale-Ruby-Gem) it says it means the environments that _polls for translations from localeapp.com by default on every request_.

It looks like the documentation from the wiki is the correct one. If so, could you update the documentation of the code?

**Comment by thibaultdalban** [comment]
Hi @redbar0n,

Thank you for your feedback, we will update the doc to clarify these points !

Cheers,
Thibault

**Comment by tjouan** [comment]
> Does this mean the names of environments where notifications are sent _(to localeapp.com)_ **_from**_ ?

Yes.

> This clarification is necessary to eliminate the ambiguity. As it currently stands you could interpret it as the environments that are being sent _to_.

I believe #246 should fix it, thanks!

---
> ```
> # The names of environments where updates aren't pulled
> # (defaults to 'development')
> attr_accessor :polling_environments
> ```
> This description is confusing, and maybe wrong?

After rereading the comment, and the code, I think polling do refer to `Localeapp::Poller` here, and pulling to pulling new translations.

So I think it's correct, but I'm not sure how to improve, if we change to "where polling is disabled", I'm not sure if it's better?

**Comment by redbar0n** [comment]
Thanks for fixing the documentation of `:sending_environments`

Regarding the documentation of`:polling_environments`:

> After rereading the comment, and the code, I think polling do refer to Localeapp::Poller here, and pulling to pulling new translations. 

Pulling from where? From the localeapp service, right?
After all, Localeapp::Poller will first _poll_ the localeapp service for updates, and then _pull_ (and sync) those updates. In that case it isn't correct that :polling_environments is the "names of environments where updates **_aren't_** pulled". It's actually the names of environments where updates **_are_** pulled. Right? 

In any case, I would suggest avoid using the words polling and pulling interchangeably, as it may lead to confusion (someone might even think you refer to a _git pull_, which is what one would do when updating the localeapp translation file from your own project's git repo).

> So I think it's correct, but I'm not sure how to improve, if we change to "where polling is disabled", I'm not sure if it's better?

Well, according to the aforementioned wiki entries, and from what I understand, it is actually supposed to be "where polling is enabled".

If I am not entirely mistaken in this, I suggest changing it to this (to be as descriptive and helpful as possible, since it also provides crucial information regarding the latency impact on the app):

```
# The names of environments where localeapp will poll for translations
# from localeapp.com (to check for new translations there) on every
# page request to your app's website.
# (defaults to 'development')
attr_accessor :polling_environments
```

**Comment by tjouan** [comment]
> Pulling from where? From the localeapp service, right?

Yes

> […] It's actually the names of environments where updates are pulled. Right?

Yes sorry, I was mistaken when reading the code (in part due to usage of a method named `polling_disabled?`).

I have only one concern with your comment suggestion, I would avoid mentioning "localeapp.com" as I don't fully understand what it refers to in this context, and technically we do not use this FQDN at all (neither the API service or the gem).

What do you think of:

``` diff
diff --git a/lib/localeapp/configuration.rb b/lib/localeapp/configuration.rb
index 5db3e9e..1522659 100644
--- a/lib/localeapp/configuration.rb
+++ b/lib/localeapp/configuration.rb
@@ -46,7 +46,9 @@ class Configuration
     # (defaults to 'development')
     attr_accessor :reloading_environments
 
-    # The names of environments where updates aren't pulled
+    # The names of environments where localeapp will poll for translations from
+    # Localeapp API (to check for new translations there) on every page request
+    # to your app's website.
     # (defaults to 'development')
     attr_accessor :polling_environments
```

**Comment by redbar0n** [comment]
Great!

Yeah, Localeapp API is even better and more precise. I just think of localeapp.com when I think of the service, that's why. :)

cheers

**Comment by tjouan** [comment]
Most of the time the API service will be at
`https://api.localeapp.com/`, but not sure it helps to mention it, as
a new user to the gem Localeapp API is same meaning I think, and it's
easier to maintain the gem if we don't hardcode URI or stuff like
that :-)

#248 should addresses last problem mentioned in this issue.

Thanks again!
