### ISSUE TITLE
Can't add new locale

### ISSUE THREAD

**Issue by azelma** [Locale/localeapp#166]
I'm working on adding a locale to my project, and can't seem to get it to populate in localeapp.com
If I try to add a locale in localeapp.com I get a 500 error.
If I add it via the command line I get:
```
$ localeapp push locales/foo.yml 
Localeapp Push

Pushing file foo.yml:
Success!

locales/foo.yml queued for processing.
```
But nothing is updating on the web interface.

**Comment by thibaultdalban** [comment]
Hi @azelma,

I've checked the reports of your imports and it seems that your file is not valid :
```
This file is not valid YAML. The parser reported the following message : (<unknown>): could not find expected ':' while scanning a simple key at line 2197 column 11
```

Could you please open a ticket directly into Locale, so we could exchange informations about your project and keep your privacy safe :)

Cheers,
Thibault

**Comment by azelma** [comment]
Thanks @thibaultdalban. I opened the issue here since I wasn't sure where to do so in Locale, I assume you mean the support link? I will close this and follow up there.
