### ISSUE TITLE
Localeapp translations conflicts on topic branch workflow

### ISSUE THREAD

**Issue by avidenov** [Locale/localeapp#168]
We are using Localeapp for some time and we are really happy with it. Recently we struggle resolving some conflicts caused by our topic branch workflow.

Lets say we have:
* Develop branch for staging
* *B1* and **B2** topic branches
* *D1* and **D2** developers
* Automatic polling is turned off.

**Issue with Rename / Delete key** 

* Developer *D1* is working on branch *B1* and renames/deletes a key from the app. 
* Developer **D2** is working on branch **B2** and it adds some keys. 
* Developer *D1* does `localeapp pull` to get the *.yml files with deleted keys. It grabs as well the new keys, added by **D2**. This is not a problem.
* Developer **D2** does `localeapp pull` to get the *.yml files with the added keys. The key which is deleted from *D1* is now also deleted in **B2** and **D2** have a problem.

Further in the process even if **D2** is handling its work without a problem, when we come to merging *B1* or **B2** to develop branch we have another issue following the case above:

* Developer *D1* is still working on *B1* branch.
* Developer **D2** is ready with it's work on **B2** and merges the **B2** branch to the develop branch. In this moment the removed key from Developer *D1* is also removed from the develop branch and we have a missing translation and failing specs in our develop branch.

Can you suggest some good practices for handling this kind of issues?

**Comment by michaelbaudino** [comment]
Hi,
Unfortunately, there is no easy way to work around that problem, as we are not providing branch-aware-ness yet (it has a lot of implementation side effects that complexifies the use of the service so it's not even sure we'll provide it in the future).
I'm sorry it's problably not the answer you were expecting, but we do not have found a good way to workaround this issue yet :disappointed:
