### ISSUE TITLE
0.9.1 regression on Rails 4.0

### ISSUE THREAD

**Issue by oree** [Locale/localeapp#169]
Calling `I18n.t(nil)` fails with

    NoMethodError: undefined method `titleize' for nil:NilClass

Gem version 0.9.0 used to return the string "translation missing: en.no key", as does plain Rails 4 without the localeapp gem.

**Comment by michaelbaudino** [comment]
Arghm, what's your exact Rails version please ?

**Comment by oree** [comment]
I'm on 4.0.13 (the latest on 4.0).

**Comment by michaelbaudino** [comment]
This should be fixed in freshly released 0.9.2 version of the gem.

**Comment by oree** [comment]
Works, thanks!
