### ISSUE TITLE
How can I use other separator than period?

### ISSUE THREAD

**Issue by mgz** [Locale/localeapp#170]

**Comment by michaelbaudino** [comment]
Hi @mgz I'm sorry I don't really understand what you mean ?
Can you give me a bit more context ? Which file type ? Which class/method ? What are you trying to do ?
If you have some code to show, it would be even better.

**Comment by michaelbaudino** [comment]
@mgz Any update ?
I'm closing this for now, feel free to reopen if you have more info and are still impacted by this issue.
