### ISSUE TITLE
Add `localeapp cp`

### ISSUE THREAD

**Issue by aaronjensen** [Locale/localeapp#172]
Once a key/string is in production in our environment it is not safe to remove it or rename it. Our typical rename workflow is that we copy key1 to key2, deploy, then delete key1. We wrote a small script to do the copy for us, but it would be nice if it were built in to locale, so I could just do: 

``` bash
$ localeapp cp key1 key2
```

**Comment by michaelbaudino** [comment]
Hi @aaronjensen,

Thanks for this idea, we just added it to our features todo list. Feel free to submit a PR if you have some working and tested code, indeed :smiley:

**Comment by Zaifor** [comment]
Any update on this?

**Comment by thibaultdalban** [comment]
Hi @Zaifor,

This feature will be available in a couple of days. I will let you know when it will be released !

**Comment by michaelbaudino** [comment]
This is finally fixed in gem version `3.1.0`, we hope you'll enjoy it.
