### ISSUE TITLE
Frequent errors on push

### ISSUE THREAD

**Issue by brauliobo** [Locale/localeapp#174]
I'm having frequent `error: closed stream` when trying to push the `config/locales` dir and I can't complete the push as it will restart again next time I try.

**Comment by michaelbaudino** [comment]
Did you try to push a directory ? Because it is not supported yet but the feature is on our todo-list.
Please push one file at a time, for the moment.

**Comment by brauliobo** [comment]
@michaelbaudino The official docs recommend push the `config/locales` directory.

**Comment by michaelbaudino** [comment]
Ho my bad, yes, of course! I mixed up with another feature we have in our todo list.

What's the size of the YAML files you're trying to push and what's your internet connection upload bandwidth? It may fail if the upload lasts longer than 30 seconds because of Heroku constraints.

**Comment by brauliobo** [comment]
Currently the `config/locales` only have the standard rails' locales, but my internet connection is pretty slow.

**Comment by michaelbaudino** [comment]
Can you say if it may take longer than 30 seconds to upload ?

On Wed, Jul 1, 2015 at 6:40 PM, Bráulio Bhavamitra <notifications@github.com
> wrote:

> Currently the config/locales only have the standard rails' locales, but
> my internet connection is pretty slow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Locale/localeapp/issues/174#issuecomment-117743654>.
>



-- 
Michael Baudino
@michaelbaudino
+33 (0) 7.61.90.93.62
Alpine Lab
1 rue de la Martinière
69001 Lyon

**Comment by brauliobo** [comment]
yeah, as the folder has a lot of files and upload was slow, probably yes

**Comment by michaelbaudino** [comment]
OK I'm closing this for now, because there's nothing quick'n'easy we can do, really.
Can you try on a faster internet connection ?
