### ISSUE TITLE
XSS issue in `Localeapp::MimicRailsMissingTranslationDisplay`

### ISSUE THREAD

**Issue by grekko** [Locale/localeapp#176]
The `module Localeapp::MimicRailsMissingTranslationDisplay` contains an XSS issue that has been fixed in rails, see: https://github.com/rails/rails/commit/e8d57f361a9982382f75449ec0d65d6c798b9ce2

The [issue](https://github.com/Locale/localeapp/blob/master/lib/localeapp/rails/mimic_rails_missing_translation_display.rb#L16) is when a undefined translation key includes HTML (e.g. non-validated user-input). In the referenced patch of rails original `TranslationHelper` this is solved by `escaping` those keys manually.

Please let me know if you are interested in a PR to propose a fix for that issue.

**Update**
I accidently pointed in the wrong direction with this issue. It actually lies in the `MimicRailsMissingTranslationDisplay`-Module not in the `TranslationHelperRails23MonkeyPatch`-Module.

**Comment by michaelbaudino** [comment]
Ho thanks for noticing this, we'd actually love a PR, indeed :heart:

**Comment by grekko** [comment]
@michaelbaudino I created a [PR](https://github.com/Locale/localeapp/pull/177) proposing a change to the `Localeapp::MimicRailsMissingTranslationDisplay`-behavior.

I could not get the test working without MonkeyPatching `String`. I'd prefer to make it work with rspec-mocks but this seems to be [a new Feature](https://github.com/rspec/rspec-mocks/issues/175) of rspec3.

**Comment by tjouan** [comment]
Fixed by #183.
