### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by phstc** [Locale/localeapp#178]
Hey,

Every time we push a blank key or add a new one in one locale without adding it in others, when we `localeapp pull`, localeapp returns the key with a trailing whitespace:

```yaml
my_new_key: # new key
```

instead of:

```yaml
my_new_key:# new key
```

And as most of the text editors we use for coding, are configured to auto remove trailing whitespace, every time we change something on these files and save, we get a big git diff, because of all those whitespaces that get removed.

Is it possible (maybe via a configuration) to stop adding trailing whitespaces?

Thanks

**Comment by michaelbaudino** [comment]
Hi Pablo,

Unfortunately, this is totally out of control on our side: it depends on the YAML parser/emitter you are using, which can change a lot from a system to another. It can be multiple gems (Syck, Psych, ...) in multiple versions or even system libraries (libyaml, ...).

Sometimes you may even notice totally different syntaxes from one developer system to another (specially between different OSes).

I'm really sorry about that, but there's no way for us to fix this :disappointed:

**Comment by phstc** [comment]
@michaelbaudino not sure if I could follow you. For example if I go to localeapp.com, add a new key  `test_key` in `en`, but not in `pt-BR`, then on my machine, I `localeapp pull`, it's going to download the `pt-BR` with `test_key: ` (with a trailing space).

So you are saying that `localeapp pull` uses a local gem, which is the one adding the trailing space?

**Comment by dmitriy-sqrt** [comment]
Any updates on this one?

**Comment by Shuiei** [comment]
bump

**Comment by pirj** [comment]
Emission of the trailing whitespace was [fixed in `libyaml` 0.2.5](https://github.com/yaml/libyaml/issues/46).

Update your `libyaml` and accept all the changes to locale files after `localeapp pull`.

**Comment by ryanb** [comment]
Run `Psych.libyaml_version` to see which version you are using. You'll need to reinstall Ruby after upgrading `libyaml` to get the new version.
