### ISSUE TITLE
Deprecation warnings on Rails 5

### ISSUE THREAD

**Issue by cannikin** [Locale/localeapp#186]
`DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.`

`DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead.`

Let me know if you'd like a pull request that fixes these!

**Comment by michaelbaudino** [comment]
Hi @cannikin,

If it's backward compatible, I would love too, indeed :heart:

**Comment by michaelbaudino** [comment]
This should have been fixed in https://github.com/Locale/localeapp/pull/200
