### ISSUE TITLE
Is `other` key restricted?

### ISSUE THREAD

**Issue by BroiSatse** [Locale/localeapp#188]
Hi,

I've been trying to push locales with `other` key - push was successful, but on each pull those keys are removed. I've tried to add this key directly via localeapp website, but got an error that this key is used as a namespace and such a key cannot be created. Is it localeapp restriction?

**Comment by michaelbaudino** [comment]
Hi @BroiSatse,

Yes, `other` is used for pluralization (like `one`, `few`, ...) and is such not accepted as a key name to avoid confusion.

**Comment by BroiSatse** [comment]
@michaelbaudino - Great, thanks for quick answer. :)
