### ISSUE TITLE
Missing :many in Polish pluralization

### ISSUE THREAD

**Issue by ezwelty** [Locale/localeapp#189]
The CLDR plural rules (http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html) for Polish (pl) specifies four keys: one, few, many, and other

However, localeapp only generates one, few, and other for Polish pluralization. The missing many key results in I18n::InvalidPluralizationData errors in my Rails apps.

**Comment by michaelbaudino** [comment]
Hi @ezwelty,

Thanks for mentioning this to us :+1: 

We actually use the [i18n](https://github.com/svenfuchs/i18n) gem that only defines `one`, `few` and `other` as pluralizations available for Polish: https://github.com/svenfuchs/i18n/blob/master/test/test_data/locales/plurals.rb#L77

That's where the fix belongs. Can you create a PR or an issue there (it always has more weight from a native speaker) ? If not, let me know, I'll do it myself :+1:

**Comment by ezwelty** [comment]
Hi @michaelbaudino,

Issue raised: https://github.com/svenfuchs/i18n/issues/339
However, you may want to consider basing your pluralizations on those of the more actively maintained rails-i18n gem (https://github.com/svenfuchs/rails-i18n/blob/master/spec/unit/pluralization_spec.rb#L567).

**Comment by michaelbaudino** [comment]
Interesting, I'll give a look at what they do, because `rails-i18n` actually uses `i18n` under the hood: https://github.com/svenfuchs/rails-i18n/blob/master/rails-i18n.gemspec#L21

Thanks for reporting this anyway :+1:

**Comment by ezwelty** [comment]
The patch has been applied: https://github.com/svenfuchs/i18n/pull/346!
