### ISSUE TITLE
Disable missing translations in a specific controller

### ISSUE THREAD

**Issue by jkostolansky** [Locale/localeapp#190]
I want to disable sending missing translations for a specific controller. I have tried to skip `send_missing_translations` callback. And it it works, kind of. It doesn't send the missing translation, however, it adds it to `Localeapp.missing_translations` (due to `Localeapp::ExceptionHandler`) and the key is sent in the next request (in another controller).

Is there a way to disable not only sending, but also collecting missing translations for a specific controller?

**Comment by michaelbaudino** [comment]
Hi @jkostolansky,

Thanks for mentioning this, unfortunately, as you noticed, we do not have an option to disable adding missing translations to `Localeapp.missing_translations` at the moment. I just added it to our todolist.

Depending on what you're trying to achieve here, another option may be to namespace all translations in this controller and to [blacklist this namespace](https://github.com/Locale/localeapp#blacklisting-keys-and-namespaces-rails-only).
