### ISSUE TITLE
localeapp.com down

### ISSUE THREAD

**Issue by mipearson** [Locale/localeapp#192]
As the website is down, I can't find a proper support channel to contact you on, so I'm sending it to places that you might see it.

![image](https://cloud.githubusercontent.com/assets/97317/16904617/9e413746-4cdc-11e6-853d-7ff09dc95da2.png)

**Comment by michaelbaudino** [comment]
Thanks a lot for mentioning it @mipearson, the Heroku routing is now fixed, we're absolutely sorry about that!
