### ISSUE TITLE
Incompatible with Ruby 2.4: dependency on json gem ~>1.8

### ISSUE THREAD

**Issue by cannikin** [Locale/localeapp#208]
Ruby 2.4 got rid of BigNum and FixNum but the version of the json gem that the localeapp gem depends on still uses these. You need json >= 2.0 in order to get the 2.4-compatible version.

**Comment by cannikin** [comment]
I've noticed another gem remove the `json` dependency completely and instead add `s.required_ruby_version = Gem::Requirement.new('>= 1.9.3')` to their gemspec instead.

**Comment by tjouan** [comment]
hello @cannikin,

thank you for reporting this issue, we are going to discuss
simplifying (or just changing) the gem dependency requirements very
soon, and discuss again PR #203 which indirectly is related.

**Comment by tjouan** [comment]
We choose to drop support for some old ruby (MRI) releases, and
started working on it.

Then if needed we'll make additional changes to support ruby 2.4, but
just dropping support for old versions might be enough.

**Comment by tjouan** [comment]
We haven't added ruby 2.4 support officially yet, we still have
something to fix under test environment. But FYI, the `master` branch
should now support ruby 2.4.
Soon we will make a new release of the gem.

**Comment by tjouan** [comment]
hello @cannikin,

Our last release of the gem, version 2.1.1 should solve current issue.

I'm closing this, don't hesitate to let us know if you discover new
issue with ruby 2.4.

**Comment by cannikin** [comment]
Thank you! :)
