### ISSUE TITLE
Localeapp pull not working

### ISSUE THREAD

**Issue by yozzz** [Locale/localeapp#237]
When i make ```localeapp pull``` i get error:
```
Localeapp Pull
Fetching translations:
D, [2017-03-21T12:46:34.794417 #3318] DEBUG -- : ** [Localeapp] API CALL: get https://api.localeapp.com/v1/projects/my_project_key/translations/all.yml
D, [2017-03-21T12:46:34.794507 #3318] DEBUG -- : ** [Localeapp] ATTEMPT 1
error: key not found: :ciphers
```
Ruby 2.4.0
Localeapp 2.1.1

**Comment by tjouan** [comment]
We use rest-client but it does not work on ruby built with OpenSSL 1.1:
https://github.com/rest-client/rest-client/issues/569

It seems it was fixed in rest-client 2, can you try to update it?
