### ISSUE TITLE
Broken with I18n >= 1.9.0

### ISSUE THREAD

**Issue by fabn** [Locale/localeapp#287]
Having this gem in bundle make app unusable when `I18n >= 1.9.0` since they removed `i18n/core_ext/hash` in ruby-i18n/i18n#573

**Comment by ryanb** [comment]
I submitted PR #288 to address this. You can use my branch until this is merged.

```
gem 'localeapp', github: 'ryanb/localeapp', branch: 'i18n-1-9'
```

**Note:** I haven't tested it beyond running the included specs.

**Comment by fabn** [comment]
Thanks @ryanb

**Comment by thibaultdalban** [comment]
Thank you for reporting this @fabn 🙏  and thank you to @ryanb for fixing it 💪 
V3.3.0 fixes the issue 🚀
